#!/usr/bin/env node
/**
 * Generates the third-party notice file that ships beside `Fetchpath.exe`.
 *
 * The package graph comes from `Cargo.lock`, so the list cannot drift away from
 * what is actually built. Licenses come from two places, and the file says
 * which for every row:
 *
 *   - **Read from the crate.** When the crate source is in the local Cargo
 *     registry, its `Cargo.toml` `license` field is read directly.
 *   - **Recorded by a maintainer.** For the statically linked C libraries and
 *     anything the registry does not hold, the value comes from `curated.json`
 *     in this directory, which records where a person checked it.
 *
 * A crate with neither is listed as unresolved and the run fails, so a new
 * dependency cannot slip into a release with no license recorded.
 *
 *   node tools/licenses/generate.mjs           # write the notices file
 *   node tools/licenses/generate.mjs --check   # fail if it is out of date
 */

import { readFile, writeFile, readdir } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = fileURLToPath(new URL('../../', import.meta.url));
const lockPath = path.join(root, 'Cargo.lock');
const curatedPath = path.join(root, 'tools/licenses/curated.json');
const outputPath = path.join(root, 'apps/desktop/src-tauri/THIRD-PARTY-NOTICES.md');

const checkOnly = process.argv.includes('--check');

/** Minimal TOML reader for the shapes Cargo.lock and Cargo.toml actually use. */
function parseLock(text) {
  const packages = [];
  let current = null;
  for (const rawLine of text.split(/\r?\n/)) {
    const line = rawLine.trim();
    if (line === '[[package]]') {
      current = {};
      packages.push(current);
      continue;
    }
    if (line.startsWith('[') && line !== '[[package]]') {
      current = null;
      continue;
    }
    if (!current) continue;
    const match = line.match(/^(name|version|source)\s*=\s*"(.*)"$/);
    if (match) current[match[1]] = match[2];
  }
  return packages;
}

/** Reads the `license` field out of a crate's own Cargo.toml. */
function licenseFromManifest(text) {
  // Stop at the first section after [package]; a dependency's own
  // `license = ...` key would otherwise be mistaken for the crate's.
  const lines = text.split(/\r?\n/);
  let inPackage = false;
  for (const rawLine of lines) {
    const line = rawLine.trim();
    if (line.startsWith('[')) {
      inPackage = line === '[package]';
      continue;
    }
    if (!inPackage) continue;
    const match = line.match(/^license\s*=\s*"(.*)"$/);
    if (match) return match[1];
    if (/^license\s*=\s*\{.*workspace\s*=\s*true/.test(line)) return 'workspace';
  }
  return null;
}

async function registrySources() {
  // Every configured CARGO_HOME the repository might have used.
  const candidates = [
    process.env.CARGO_HOME,
    path.join(process.env.USERPROFILE ?? process.env.HOME ?? '', '.cargo'),
  ].filter(Boolean);

  const roots = [];
  for (const home of candidates) {
    const registry = path.join(home, 'registry', 'src');
    try {
      for (const entry of await readdir(registry, { withFileTypes: true })) {
        if (entry.isDirectory()) roots.push(path.join(registry, entry.name));
      }
    } catch {
      // This CARGO_HOME does not exist on this machine; try the next.
    }
  }
  return roots;
}

async function main() {
  const [lockText, curatedText] = await Promise.all([
    readFile(lockPath, 'utf8'),
    readFile(curatedPath, 'utf8'),
  ]);
  const curated = JSON.parse(curatedText);
  const packages = parseLock(lockText);
  const sources = await registrySources();

  const workspaceLicense = licenseFromManifest(await readFile(path.join(root, 'Cargo.toml'), 'utf8'))
    ?? 'MIT OR Apache-2.0';

  const rows = [];
  const unresolved = [];

  for (const pkg of packages) {
    // A package with no `source` is one of ours, covered by the repository license.
    if (!pkg.source) continue;

    const curatedEntry = curated.crates?.[pkg.name];
    if (curatedEntry) {
      rows.push({ ...pkg, license: curatedEntry.license, origin: curatedEntry.evidence });
      continue;
    }

    let license = null;
    for (const source of sources) {
      try {
        const manifest = await readFile(path.join(source, `${pkg.name}-${pkg.version}`, 'Cargo.toml'), 'utf8');
        license = licenseFromManifest(manifest);
        if (license === 'workspace') license = workspaceLicense;
        if (license) break;
      } catch {
        // Not vendored under this registry root.
      }
    }

    if (license) rows.push({ ...pkg, license, origin: 'Read from the crate manifest in the local registry' });
    else unresolved.push(pkg);
  }

  rows.sort((a, b) => a.name.localeCompare(b.name));

  const generated = [
    '<!-- Generated by `node tools/licenses/generate.mjs`. Do not edit by hand. -->',
    '',
    '# Fetchpath third-party notices',
    '',
    'This file ships beside `Fetchpath.exe` so the notices travel with the binary.',
    '',
    `Fetchpath's own source is licensed **${workspaceLicense}** (\`[workspace.package] license\``,
    'in the repository root `Cargo.toml`).',
    '',
    `The table below is generated from \`Cargo.lock\`, so it lists the ${rows.length} third-party`,
    'packages that are actually part of a build rather than a hand-maintained list.',
    'The **Source of the license value** column says, for every row, whether the',
    "value was read from the crate's own manifest or recorded by a maintainer.",
    '',
    ...curated.preamble,
    '',
    '## Rust packages',
    '',
    '| Package | Version | License | Source of the license value |',
    '| --- | --- | --- | --- |',
    ...rows.map((row) => `| ${row.name} | ${row.version} | ${row.license} | ${row.origin} |`),
    '',
    ...curated.appendix,
    '',
  ].join('\n');

  if (checkOnly) {
    const existing = await readFile(outputPath, 'utf8').catch(() => '');
    if (existing !== generated) {
      throw new Error(
        `${path.relative(root, outputPath)} is out of date.\n` +
          'Run `node tools/licenses/generate.mjs` and commit the result.',
      );
    }
  } else {
    await writeFile(outputPath, generated);
    process.stdout.write(`Wrote ${path.relative(root, outputPath)} with ${rows.length} packages.\n`);
  }

  if (unresolved.length) {
    throw new Error(
      'No license could be established for:\n' +
        unresolved.map((pkg) => `  ${pkg.name} ${pkg.version}`).join('\n') +
        '\nAdd each one to tools/licenses/curated.json with the evidence that was checked.',
    );
  }
  if (checkOnly) process.stdout.write('THIRD-PARTY-NOTICES.md is up to date.\n');
}

main().catch((error) => {
  console.error(error.message);
  process.exitCode = 1;
});
