[package]
name = "fetchpath-core"
version = "0.1.0"
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
curl = { version = "0.4.50", features = ["static-curl", "http2"] }
fetchpath-http = { path = "../fetchpath-http" }
fetchpath-metalink = { path = "../fetchpath-metalink" }
fetchpath-storage = { path = "../fetchpath-storage" }
sha2 = "0.10.9"
uuid = { version = "1.18.1", features = ["v4"] }
