// Checks on the files a release ships that no compiler enforces: the pinned
// media-tool manifest, the generated third-party notices, and the installer's
// data-removal hook.
//
// These are all things a maintainer could plausibly get wrong by hand and that
// would only be noticed by a user after the fact.

import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFile, access } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = fileURLToPath(new URL('../../', import.meta.url));
const read = (relative) => readFile(path.join(root, relative), 'utf8');

test('the media tool manifest is complete enough to act on', async () => {
  const manifest = JSON.parse(await read('apps/desktop/src-tauri/media-tools.json'));
  const names = manifest.tools.map((tool) => tool.name);
  assert.ok(names.includes('yt-dlp'), `expected yt-dlp in ${names.join(', ')}`);
  assert.ok(names.includes('ffmpeg'), `expected ffmpeg in ${names.join(', ')}`);

  for (const tool of manifest.tools) {
    assert.match(tool.url, /^https:\/\//, `${tool.name} must be fetched over TLS`);
    assert.match(tool.checksumSource, /^https:\/\//, `${tool.name} needs a publisher checksum source`);
    assert.ok(tool.license, `${tool.name} needs a license to show before downloading`);
    assert.ok(['executable', 'zip'].includes(tool.kind), `${tool.name} has an unknown kind ${tool.kind}`);
    // A digest is either absent, which refuses the download, or a real SHA-256.
    // A truncated or malformed value would fail the comparison at install time
    // with a confusing message instead of being caught here.
    if (tool.sha256) {
      assert.match(tool.sha256, /^[0-9a-f]{64}$/i, `${tool.name} has a malformed sha256`);
    }
  }
});

test('an unpinned manifest entry is visible rather than silently broken', async () => {
  const manifest = JSON.parse(await read('apps/desktop/src-tauri/media-tools.json'));
  const unpinned = manifest.tools.filter((tool) => !tool.sha256);
  if (!unpinned.length) return;
  // The application refuses to download an unpinned artifact, so the manifest
  // has to carry the note that says how to pin one. Losing that comment would
  // leave a maintainer with a refusal and no instruction.
  const comment = (manifest._comment ?? []).join(' ');
  assert.match(
    comment,
    /pin\.mjs/,
    'an unpinned entry exists, so the manifest must say how to record a digest',
  );
});

test('the third-party notices are generated, not hand-edited', async () => {
  const notices = await read('apps/desktop/src-tauri/THIRD-PARTY-NOTICES.md');
  assert.match(
    notices,
    /Generated by `node tools\/licenses\/generate\.mjs`/,
    'the notices file must carry its generator banner',
  );
  assert.match(notices, /\| Package \| Version \| License \| Source of the license value \|/);
  // The generator fails on an unresolved crate, so an empty table would mean
  // the file was replaced by hand with something that skipped that check.
  const rows = notices.split('\n').filter((line) => /^\| \S+ \| \d/.test(line));
  assert.ok(rows.length > 100, `expected a full package table, found ${rows.length} rows`);
});

test('uninstall asks one question about user data and reverses what install added', async () => {
  const config = JSON.parse(await read('apps/desktop/src-tauri/tauri.conf.json'));
  const hook = config.bundle?.windows?.nsis?.installerHooks;
  assert.ok(hook, 'no installerHooks entry, so uninstall would not reverse the PATH or browser registration');

  const hookPath = path.join(root, 'apps/desktop/src-tauri', hook.replace(/^\.\//, ''));
  await access(hookPath);
  const source = await readFile(hookPath, 'utf8');

  // User data is the bundler's single, unticked "Delete the application data"
  // checkbox. A second prompt here once contradicted it: ticking the box and
  // answering No still deleted the data. The hook must neither ask nor delete.
  assert.doesNotMatch(source, /^\s*MessageBox/m, 'the hook must not ask a second question about user data');
  assert.doesNotMatch(source, /^\s*RMDir/m, 'the hook must not delete user data itself');

  // What install added, uninstall removes: the PATH entry, while the script
  // that removes it still exists, and exactly the three browser keys.
  const preUninstall = source.slice(source.indexOf('!macro NSIS_HOOK_PREUNINSTALL'));
  assert.match(preUninstall, /FETCHPATH_USER_PATH Remove/, 'uninstall must remove the PATH entry');
  const deleted = [...source.matchAll(/^\s*DeleteRegKey HKCU "([^"]+)"/gm)].map((match) => match[1]).sort();
  const host = '\\NativeMessagingHosts\\${FETCHPATH_HOST}';
  assert.deepEqual(deleted, [
    `Software\\Google\\Chrome${host}`,
    `Software\\Microsoft\\Edge${host}`,
    `Software\\Mozilla${host}`,
  ]);
});

test('the desktop can pick a folder, which settings and media setup both need', async () => {
  const capability = JSON.parse(await read('apps/desktop/src-tauri/capabilities/default.json'));
  assert.ok(
    capability.permissions.includes('dialog:allow-open'),
    'without dialog:allow-open the default-folder and media-tools pickers fail at runtime',
  );
});
