[package]
name = "fetchpath-http"
version = "0.1.0"
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
curl = { version = "0.4.50", features = ["static-curl", "http2", "protocol-ftp"] }
curl-sys = { version = "0.4.90", default-features = false }
percent-encoding = "2.3.2"
russh = { version = "0.63.3", default-features = false, features = ["flate2", "ring", "rsa"] }
russh-sftp = "3.0.0"
serde_json = "1.0.145"
tokio = { version = "1.48.0", features = ["io-util", "net", "rt", "time"] }
url = "2.5.8"
